# Site settings
title: 匠人造物
subtitle: [认真地探索新世界，分享每一份收获]
keywords: jrwork
description: 我………………………………。微信公众号：匠人造物.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jrwork.cn/" # 你的域名
page_no_title: "Thomas Teng's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: Thomas Teng
email: xbteng@outlook.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接

#  - title:
#    url: http://jekyllcn.com/
  - title: 欢迎订阅本站 RSS
    url: https://jrwork.cn/feed.xml
  - title: Jekyll blog system
    url: http://jekyllcn.com/